=== llamas-in-pajamas/human-machine-communication/FilmLibrarySpecs/movies.dtd
<!ELEMENT Catalogue (AuthorRepository, MovieRepository)> 
<!ATTLIST Catalogue
    xmlns:i CDATA #IMPLIED
    xmlns CDATA #IMPLIED
>

<!ELEMENT AuthorRepository (Authors)>
<!ATTLIST AuthorRepository
    z:Id ID #REQUIRED
    xmlns:z CDATA #IMPLIED
>

<!ELEMENT Authors (Author*)>
<!ELEMENT Author (FirstName*, LastName*)>
<!ATTLIST Author
    z:Id ID #IMPLIED
    z:Ref NMTOKEN #IMPLIED
>

<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>

<!ELEMENT MovieRepository (Movies)>
<!ATTLIST MovieRepository
    z:Id ID #REQUIRED
    xmlns:z CDATA #IMPLIED
>

<!ELEMENT Movies (Movie*)>
<!ELEMENT Movie (Author, Budget, Description, Rating, ReleaseDate, Title)>

<!ATTLIST Movie genre (drama|horror|action|adventure) #REQUIRED>

<!ELEMENT Budget (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Rating (#PCDATA)>
<!ELEMENT ReleaseDate (#PCDATA)>
<!ELEMENT Title (#PCDATA)>

=== llamas-in-pajamas/human-machine-communication/movies_2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Catalogue SYSTEM "movies.dtd">
<?xml-stylesheet type="text/css" href="movies.css"?>
<Catalogue xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/FilmLibrary">
 <AuthorRepository z:Id="i1" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/">
  <Authors>
   <Author z:Id="i2">
    <FirstName>Jairo</FirstName>
    <LastName>Johnston</LastName>
   </Author>
   <Author z:Id="i3">
    <FirstName>Jimmy</FirstName>
    <LastName>Murray</LastName>
   </Author>
   <Author z:Id="i4">
    <FirstName>Muhammad</FirstName>
    <LastName>Rippin</LastName>
   </Author>
   <Author z:Id="i5">
    <FirstName>Gussie</FirstName>
    <LastName>Rau</LastName>
   </Author>
  </Authors>
 </AuthorRepository>
 <MovieRepository z:Id="i6" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/">
  <Movies>
   <Movie>
    <Author z:Ref="i3" />
    <Budget>278430228</Budget>
    <Description>Sint est veritatis quia excepturi provident. Unde quis voluptatem soluta est. Et omnis cupiditate minima quasi quia cum. Aut deleniti aut voluptates eveniet.</Description>
    <Rating>8.34</Rating>
    <ReleaseDate>2002-12-01T00:00:00</ReleaseDate>
    <Title>Quam quam in dolores omnis aliquid animi inventore itaque.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i2" />
    <Budget>495223572</Budget>
    <Description>Magnam quam dolorem praesentium. Dolor cumque doloribus similique dolor non consequuntur. Consequatur repellendus quasi quo non aliquam velit.</Description>
    <Rating>6.46</Rating>
    <ReleaseDate>2012-11-03T00:00:00</ReleaseDate>
    <Title>Est vero consequuntur quibusdam et consequuntur quis.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i4" />
    <Budget>1962407212</Budget>
    <Description>Exercitationem nesciunt inventore officiis aliquam ducimus nisi. Voluptatem non voluptates ipsam labore non ducimus pariatur perspiciatis. Provident ut qui aut impedit qui animi.</Description>
    <Rating>2.94</Rating>
    <ReleaseDate>1998-12-17T00:00:00</ReleaseDate>
    <Title>Optio distinctio doloribus expedita sit architecto natus.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i2" />
    <Budget>1213501493</Budget>
    <Description>Officia dolores non dolorum consequatur autem incidunt sed nihil. Dolorum repudiandae aliquid aut culpa. Eum distinctio rerum voluptatem ducimus nam enim optio. Soluta nulla consequatur aut fugiat possimus tempore exercitationem. Voluptatem voluptate ipsa voluptates reiciendis ex.</Description>
    <Rating>3.14</Rating>
    <ReleaseDate>2007-02-10T00:00:00</ReleaseDate>
    <Title>Molestias est enim itaque dolor enim amet architecto.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i3" />
    <Budget>1138783414</Budget>
    <Description>Cum mollitia cupiditate et et eum officiis est provident. Quia accusamus in hic dolorum officiis perspiciatis quia possimus. Nobis provident in itaque aut alias. Delectus consequatur expedita exercitationem aliquid qui vero asperiores. Tenetur laboriosam perspiciatis non eaque nostrum qui aut.</Description>
    <Rating>6.25</Rating>
    <ReleaseDate>2017-07-27T00:00:00</ReleaseDate>
    <Title>Illum eligendi maiores neque odio.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i2" />
    <Budget>1380952229</Budget>
    <Description>Eius numquam ratione voluptatem qui rerum et quasi. Voluptatem officiis sunt aut qui porro tenetur et sint. Et unde iusto reprehenderit quo. Facere sequi nemo est aut molestiae perferendis reprehenderit. Et facilis pariatur cum quis reprehenderit cum.</Description>
    <Rating>0.57</Rating>
    <ReleaseDate>2007-02-04T00:00:00</ReleaseDate>
    <Title>Magni ut rerum enim.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i4" />
    <Budget>455420444</Budget>
    <Description>Doloremque labore cupiditate odio enim tempora dolor qui iusto. Eum autem natus exercitationem aspernatur. Eos dolor qui consequatur architecto odit.</Description>
    <Rating>0.3</Rating>
    <ReleaseDate>2003-12-11T00:00:00</ReleaseDate>
    <Title>Perspiciatis consequatur tenetur ea nemo.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i2" />
    <Budget>909652771</Budget>
    <Description>Ut et voluptas quod error ea. Quia aliquid eos qui esse aliquid ut. Sed pariatur doloremque in dicta magni illum. Et molestiae asperiores reiciendis et. Qui voluptatum in libero earum.</Description>
    <Rating>6.84</Rating>
    <ReleaseDate>2006-09-13T00:00:00</ReleaseDate>
    <Title>Est incidunt omnis provident doloribus.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i2" />
    <Budget>613856399</Budget>
    <Description>Libero magnam eligendi saepe. Non fugiat omnis ad. Cum aliquam est repellendus nihil illum sunt molestiae rerum.</Description>
    <Rating>8.73</Rating>
    <ReleaseDate>2009-11-13T00:00:00</ReleaseDate>
    <Title>Non nam nihil maxime velit aliquam debitis necessitatibus.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i2" />
    <Budget>633046198</Budget>
    <Description>Et architecto est laborum et incidunt aut. Quam atque ut sed omnis asperiores nobis error itaque. Id sapiente error laboriosam aliquam excepturi consequatur eum. Deleniti placeat sit rerum quaerat omnis quaerat officiis dolor.</Description>
    <Rating>1.56</Rating>
    <ReleaseDate>2007-04-01T00:00:00</ReleaseDate>
    <Title>Quia assumenda qui totam qui cupiditate voluptatem voluptatem laudantium.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i2" />
    <Budget>1869657609</Budget>
    <Description>Eligendi itaque vitae iste sed accusantium praesentium illum. Est dolorem veniam fuga modi. Sed aut nihil exercitationem. Molestias laborum voluptas aperiam. Dolores aut vel itaque.</Description>
    <Rating>3.38</Rating>
    <ReleaseDate>1997-07-17T00:00:00</ReleaseDate>
    <Title>Ut a velit facere inventore.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i4" />
    <Budget>846502768</Budget>
    <Description>Et incidunt esse commodi est error rerum ullam. Tempora odio dolor magnam eaque in harum eius beatae. Quae voluptate eaque repudiandae facilis. Aut et et dicta accusamus neque eligendi tempore nemo. Veritatis nihil qui et sed.</Description>
    <Rating>5.67</Rating>
    <ReleaseDate>2018-09-26T00:00:00</ReleaseDate>
    <Title>Pariatur et aut autem.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i2" />
    <Budget>337945831</Budget>
    <Description>Vel error sed voluptatibus modi illum exercitationem. Voluptatem assumenda atque soluta et. Numquam reiciendis et maxime.</Description>
    <Rating>1.09</Rating>
    <ReleaseDate>2013-04-15T00:00:00</ReleaseDate>
    <Title>Rerum eos sint non.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i5" />
    <Budget>160462709</Budget>
    <Description>A iste iure aperiam enim quisquam aut error atque. Sit sit rem vero perferendis aut maxime. Distinctio et cumque aut quidem tempore illum harum ab.</Description>
    <Rating>8.83</Rating>
    <ReleaseDate>2013-10-08T00:00:00</ReleaseDate>
    <Title>Rerum et quidem praesentium.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i5" />
    <Budget>1770186015</Budget>
    <Description>Quod illum veniam dolores omnis libero recusandae deserunt eligendi. Aut ad dolore non rerum est asperiores. Repudiandae ut hic sint quo eius.</Description>
    <Rating>2.56</Rating>
    <ReleaseDate>2015-06-10T00:00:00</ReleaseDate>
    <Title>Tempore tenetur et dolorum rerum accusamus ea.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i5" />
    <Budget>472612067</Budget>
    <Description>Nesciunt praesentium iusto ut sunt. Esse rerum doloremque recusandae ex aut consequuntur possimus. Rerum ab voluptates voluptatibus.</Description>
    <Rating>7.45</Rating>
    <ReleaseDate>2004-06-19T00:00:00</ReleaseDate>
    <Title>Dolorem aut et vero dicta porro perferendis aut aut.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i2" />
    <Budget>1659999904</Budget>
    <Description>Dolore distinctio qui enim. Excepturi laboriosam et provident ut nobis veniam. Accusamus eum dolorem non et. Ducimus labore sunt ducimus illo reprehenderit culpa vel.</Description>
    <Rating>6.49</Rating>
    <ReleaseDate>2017-01-17T00:00:00</ReleaseDate>
    <Title>Facere dignissimos eos quaerat velit corporis iste laudantium accusantium.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i3" />
    <Budget>1678051856</Budget>
    <Description>Similique atque vel at quam repellendus in. Necessitatibus nulla ducimus natus hic. Illum nesciunt non tempore.</Description>
    <Rating>1.46</Rating>
    <ReleaseDate>2002-02-13T00:00:00</ReleaseDate>
    <Title>Reiciendis optio atque maxime dicta fugiat nihil officiis reiciendis.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i3" />
    <Budget>668978039</Budget>
    <Description>Maxime nesciunt veniam debitis. Quo mollitia quidem est alias deserunt delectus voluptates. Culpa nemo suscipit corrupti in aliquam ex eos odit. Dicta id nostrum sit asperiores voluptates mollitia voluptates cupiditate.</Description>
    <Rating>8.44</Rating>
    <ReleaseDate>1999-08-30T00:00:00</ReleaseDate>
    <Title>Cumque ea nam velit veritatis dignissimos laborum aperiam.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i2" />
    <Budget>667723549</Budget>
    <Description>Sint quo sunt aliquam. Ut quos repudiandae odit. Aut ab dignissimos autem sit quam in facilis. Ea nobis dignissimos sed exercitationem quia rerum dolores. Tenetur rerum voluptatem omnis dolores id.</Description>
    <Rating>1.23</Rating>
    <ReleaseDate>2018-11-22T00:00:00</ReleaseDate>
    <Title>Eveniet velit voluptas debitis quis odit repellat.</Title>
   </Movie>
   <Movie>
    <Author z:Ref="i5" />
    <Budget>895571713</Budget>
    <Description>Aliquid eius voluptate ipsa accusantium eaque reprehenderit laborum. Quam architecto quidem quibusdam beatae voluptatum ea. A totam laudantium sit. Impedit modi quia modi vel voluptas quia exercitationem est. Minima voluptatum dolorem quam.</Description>
